name=URP2_DVI_HSTX
version=1.0.0
author=UNIT Electronics
maintainer=Cesar Bautista <ventas@uelectronics.com>, Jonathan Mejorado
sentence=Arduino library for RP2350 DVI output via HSTX
paragraph=DVI/HDMI output library for RP2350 boards using HSTX peripheral. GFX-compatible 16-bit, 8-bit palette, and text modes.
category=Display
url=https://github.com/UNIT-Electronics-MX/unit_rp2_dvi_hstx_library
architectures=rp2040
depends=Adafruit GFX Library
